"""Emit a Feast repository's `features.py` from the in-code views.

Output is Python source text. It imports `feast` when Feast runs it, not when
this module runs, so generating a repo needs no extra installed.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Any

from vmp.data.io import atomic_write_text
from vmp.features.views import FeatureView, list_views

_FEAST_TYPES = {"float": "Float32", "int": "Int64", "str": "String"}


def _ident(name: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name)


def feast_source(
    views: Iterable[FeatureView] | None = None,
    *,
    data_root: str = "data",
    project: str = "vmp",
) -> str:
    """Return the text of a Feast `features.py` for `views` (default: the registry)."""
    vs = list(views) if views is not None else list_views()
    entities = sorted({v.entity for v in vs})
    lines: list[str] = [
        f"# Generated by vmp.features.feast_export for project {project!r}. Do not edit.",
        "from datetime import timedelta",
        "",
        "from feast import Entity, FeatureView, Field, FileSource",
        "from feast.types import Float32, Int64, String",
        "",
    ]
    for e in entities:
        lines += [
            f'{_ident(e)} = Entity(name="{e}", join_keys=["{e}_id"])',
            "",
        ]
    for v in vs:
        src = f"{_ident(v.name)}_source"
        lines += [
            f"{src} = FileSource(",
            f'    path="{data_root}/{v.name}.parquet",',
            '    timestamp_field="event_ts",',
            ")",
            "",
            f"{_ident(v.name)} = FeatureView(",
            f'    name="{v.name}",',
            f"    entities=[{_ident(v.entity)}],",
            f"    ttl=timedelta(seconds={int(v.ttl_s)}),",
            "    schema=[",
        ]
        for f in v.features:
            lines.append(f'        Field(name="{f.name}", dtype={_FEAST_TYPES[f.dtype]}),')
        lines += [
            "    ],",
            "    online=True,",
            f"    source={src},",
            f'    tags={{"source": "{v.source}"}},',
            f"    description={v.description!r},",
            ")",
            "",
        ]
    return "\n".join(lines).rstrip("\n") + "\n"


def write_feast_repo(
    root: str | Path,
    views: Iterable[FeatureView] | None = None,
    *,
    data_root: str = "data",
    project: str = "vmp",
    dry_run: bool = False,
) -> dict[str, Any]:
    """Write `<root>/feature_repo/features.py`. Returns a manifest; dry_run writes nothing."""
    vs = list(views) if views is not None else list_views()
    text = feast_source(vs, data_root=data_root, project=project)
    out = Path(root) / "feature_repo" / "features.py"
    if not dry_run:
        atomic_write_text(out, text)
    return {
        "path": str(out),
        "project": project,
        "views": [v.name for v in vs],
        "entities": sorted({v.entity for v in vs}),
        "bytes": len(text.encode()),
        "dry_run": dry_run,
    }


__all__ = ["feast_source", "write_feast_repo"]
