"""Ray Serve graph tests. Dry run and config rendering only: `ray` is never imported."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from vmp.config import load_config
from vmp.serving.ray_serve import (
    DEPLOYMENTS,
    autoscaling_config,
    build_graph,
    describe_graph,
    ray_actor_options,
    serve_config_yaml,
)

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "configs" / "serving.toml"


@pytest.fixture
def config() -> dict:
    return load_config(CONFIG)


# -- no heavy import --------------------------------------------------------


def test_dry_run_does_not_import_ray(config):
    assert "ray" not in sys.modules
    build_graph(config, dry_run=True)
    serve_config_yaml(config)
    assert "ray" not in sys.modules


# -- graph description ------------------------------------------------------


def test_describe_graph_from_the_repository_config(config):
    plan = build_graph(config, dry_run=True)
    assert plan == describe_graph(config)
    assert plan["dry_run"] is True
    assert plan["app_name"] == "voice-agent"
    assert plan["route_prefix"] == "/"
    assert plan["http"] == {"host": "0.0.0.0", "port": 8000}
    assert plan["import_path"] == "vmp.serving.ray_serve:app"
    assert list(plan["deployments"]) == list(DEPLOYMENTS)
    assert plan["edges"] == [["ingress", "stt"], ["ingress", "llm"], ["ingress", "tts"]]
    assert json.loads(json.dumps(plan)) == plan  # the CLI prints it as JSON


def test_each_deployment_names_its_class_and_resources(config):
    deployments = describe_graph(config)["deployments"]
    assert [d["class"] for d in deployments.values()] == [
        "STTDeployment",
        "LLMDeployment",
        "TTSDeployment",
        "VoiceAgentIngress",
    ]
    assert deployments["stt"]["autoscaling_config"] == {
        "min_replicas": 1,
        "max_replicas": 4,
        "target_ongoing_requests": 2.0,
    }
    assert deployments["ingress"]["ray_actor_options"] == {"num_cpus": 0.5}
    assert deployments["stt"]["backend"] == "echo"
    assert deployments["tts"]["backend"] == "silent"


def test_llm_mode_selects_the_backend_and_model():
    proxy = describe_graph(
        {
            "serving": {
                "ray_serve": {"llm_mode": "openai-compat"},
                "backends": {"openai_compat": {"model": "served-model"}, "vllm": {"model": "big"}},
            }
        }
    )
    assert proxy["deployments"]["llm"]["backend"] == "openai-compat"
    assert proxy["deployments"]["llm"]["model"] == "served-model"

    engine = describe_graph(
        {
            "serving": {
                "ray_serve": {"llm_mode": "vllm"},
                "backends": {"openai_compat": {"model": "served-model"}, "vllm": {"model": "big"}},
            }
        }
    )
    assert engine["deployments"]["llm"]["backend"] == "vllm"
    assert engine["deployments"]["llm"]["model"] == "big"


def test_unknown_llm_mode_is_rejected():
    with pytest.raises(ValueError, match="llm_mode"):
        describe_graph({"serving": {"ray_serve": {"llm_mode": "guess"}}})


def test_defaults_apply_to_an_empty_config():
    plan = describe_graph({})
    assert plan["app_name"] == "voice-agent"
    assert plan["deployments"]["llm"]["backend"] == "openai-compat"
    assert plan["deployments"]["stt"]["backend"] == "echo"
    assert plan["deployments"]["llm"]["model"] is None


def test_config_sections_are_interchangeable(config):
    """The whole TOML, the `[serving]` table or the `[serving.ray_serve]` table."""
    whole = describe_graph(config)
    serving_only = describe_graph(config["serving"])
    assert whole["deployments"]["stt"]["autoscaling_config"] == (
        serving_only["deployments"]["stt"]["autoscaling_config"]
    )
    assert whole["app_name"] == serving_only["app_name"]


def test_autoscaling_and_actor_options_overrides():
    config = {
        "serving": {
            "ray_serve": {
                "llm": {"min_replicas": 2, "max_replicas": 8, "num_gpus": 1.0, "bogus": 1},
                "tts": {"num_cpus": 2.0},
            }
        }
    }
    assert autoscaling_config(config, "llm") == {
        "min_replicas": 2,
        "max_replicas": 8,
        "target_ongoing_requests": 8.0,
    }
    assert ray_actor_options(config, "llm") == {"num_cpus": 1.0, "num_gpus": 1.0}
    assert ray_actor_options(config, "tts") == {"num_cpus": 2.0}
    # A zero GPU request is left out entirely.
    assert ray_actor_options({}, "stt") == {"num_cpus": 1.0}


# -- serve config file ------------------------------------------------------


def test_serve_config_text(config):
    text = serve_config_yaml(config)
    lines = text.splitlines()

    assert lines[0].startswith("# Generated by `vmp serve ray --yaml`")
    assert "proxy_location: EveryNode" in lines
    assert "http_options:" in lines
    assert "  host: 0.0.0.0" in lines
    assert "  port: 8000" in lines
    assert "  - name: voice-agent" in lines
    assert "    route_prefix: /" in lines
    assert "    import_path: vmp.serving.ray_serve:app" in lines
    assert "    deployments:" in lines
    for klass in ("STTDeployment", "LLMDeployment", "TTSDeployment", "VoiceAgentIngress"):
        assert f"      - name: {klass}" in lines
    assert text.endswith("\n")


def test_serve_config_embeds_the_config_as_json(config):
    line = next(
        ln for ln in serve_config_yaml(config).splitlines() if "VMP_SERVING_CONFIG_JSON" in ln
    )
    embedded = line.split("VMP_SERVING_CONFIG_JSON: ", 1)[1].strip().strip("'")
    assert json.loads(embedded) == config


def test_serve_config_carries_each_deployments_scale(config):
    text = serve_config_yaml(config)
    assert "          min_replicas: 1" in text
    assert "          max_replicas: 4" in text
    assert "          target_ongoing_requests: 16.0" in text
    assert "          num_cpus: 0.5" in text
    # One autoscaling block per deployment.
    assert text.count("        autoscaling_config:") == len(DEPLOYMENTS)
    assert text.count("        ray_actor_options:") == len(DEPLOYMENTS)


def test_serve_config_declares_a_gpu_only_when_requested():
    text = serve_config_yaml({"serving": {"ray_serve": {"llm": {"num_gpus": 2.0}}}})
    gpu_lines = [ln for ln in text.splitlines() if ln.strip().startswith("num_gpus:")]
    assert gpu_lines == ["          num_gpus: 2.0"]
