"""Ray Serve deployment graph for the voice agent.

Four deployments: `STTDeployment`, `LLMDeployment` (in-process vLLM engine or a
proxy to an OpenAI-compatible server), `TTSDeployment`, and `VoiceAgentIngress`
that binds the FastAPI app from `vmp.serving.api`. `ray` is imported only inside
`build_graph(dry_run=False)`; `build_graph(..., dry_run=True)` and
`serve_config_yaml` need nothing but the standard library.
"""

from __future__ import annotations

import json
from typing import Any

from vmp.serving.backends import CONTEXT_MARKER  # noqa: F401 - re-exported for ingress prompts
from vmp.types import Utterance

DEPLOYMENTS = ("stt", "llm", "tts", "ingress")
_DEFAULT_SCALE = {
    "stt": {"min_replicas": 1, "max_replicas": 4, "target_ongoing_requests": 2},
    "llm": {"min_replicas": 1, "max_replicas": 2, "target_ongoing_requests": 8},
    "tts": {"min_replicas": 1, "max_replicas": 4, "target_ongoing_requests": 2},
    "ingress": {"min_replicas": 1, "max_replicas": 2, "target_ongoing_requests": 16},
}


def _section(config: dict[str, Any]) -> dict[str, Any]:
    """Accept the whole TOML, the `[serving]` table, or the `[serving.ray_serve]` table."""
    if "serving" in config:
        config = config["serving"]
    return config.get("ray_serve", config)


def _backends(config: dict[str, Any]) -> dict[str, Any]:
    if "serving" in config:
        config = config["serving"]
    return config.get("backends", {})


def autoscaling_config(config: dict[str, Any], name: str) -> dict[str, Any]:
    """`autoscaling_config` dict for one deployment (Ray Serve field names)."""
    rs = _section(config)
    d = dict(_DEFAULT_SCALE[name])
    d.update({k: v for k, v in rs.get(name, {}).items() if k in d})
    return {
        "min_replicas": int(d["min_replicas"]),
        "max_replicas": int(d["max_replicas"]),
        "target_ongoing_requests": float(d["target_ongoing_requests"]),
    }


def ray_actor_options(config: dict[str, Any], name: str) -> dict[str, Any]:
    rs = _section(config).get(name, {})
    out: dict[str, Any] = {"num_cpus": float(rs.get("num_cpus", 1.0))}
    if float(rs.get("num_gpus", 0.0)) > 0:
        out["num_gpus"] = float(rs["num_gpus"])
    return out


def describe_graph(config: dict[str, Any]) -> dict[str, Any]:
    """The plan returned by `build_graph(dry_run=True)`: no `ray` import."""
    rs = _section(config)
    b = _backends(config)
    llm_mode = str(rs.get("llm_mode", "openai-compat"))
    if llm_mode not in ("openai-compat", "vllm"):
        raise ValueError(f"llm_mode must be 'openai-compat' or 'vllm', got {llm_mode!r}")
    deployments = {}
    for name in DEPLOYMENTS:
        deployments[name] = {
            "class": {
                "stt": "STTDeployment",
                "llm": "LLMDeployment",
                "tts": "TTSDeployment",
                "ingress": "VoiceAgentIngress",
            }[name],
            "autoscaling_config": autoscaling_config(config, name),
            "ray_actor_options": ray_actor_options(config, name),
        }
    deployments["stt"]["backend"] = str(b.get("stt", "echo"))
    deployments["llm"]["backend"] = llm_mode
    deployments["llm"]["model"] = (
        b.get("vllm", {}).get("model")
        if llm_mode == "vllm"
        else b.get("openai_compat", {}).get("model")
    )
    deployments["tts"]["backend"] = str(b.get("tts", "silent"))
    return {
        "app_name": str(rs.get("app_name", "voice-agent")),
        "route_prefix": str(rs.get("route_prefix", "/")),
        "http": {
            "host": str(rs.get("http_host", "0.0.0.0")),
            "port": int(rs.get("http_port", 8000)),
        },
        "import_path": "vmp.serving.ray_serve:app",
        "deployments": deployments,
        "edges": [["ingress", "stt"], ["ingress", "llm"], ["ingress", "tts"]],
        "dry_run": True,
    }


def serve_config_yaml(config: dict[str, Any]) -> str:
    """Text for `serve run <file>` / `serve deploy <file>` (Ray Serve config schema).

    Rendered by string formatting: the core package has no YAML dependency.
    """
    plan = describe_graph(config)
    lines = [
        "# Generated by `vmp serve ray --yaml`. Ray Serve config schema v2.",
        "proxy_location: EveryNode",
        "http_options:",
        f"  host: {plan['http']['host']}",
        f"  port: {plan['http']['port']}",
        "applications:",
        f"  - name: {plan['app_name']}",
        f"    route_prefix: {plan['route_prefix']}",
        f"    import_path: {plan['import_path']}",
        "    runtime_env:",
        f"      env_vars:\n        VMP_SERVING_CONFIG_JSON: '{json.dumps(config)}'",
        "    deployments:",
    ]
    for name in DEPLOYMENTS:
        d = plan["deployments"][name]
        a = d["autoscaling_config"]
        lines += [
            f"      - name: {d['class']}",
            "        autoscaling_config:",
            f"          min_replicas: {a['min_replicas']}",
            f"          max_replicas: {a['max_replicas']}",
            f"          target_ongoing_requests: {a['target_ongoing_requests']}",
            "        ray_actor_options:",
        ]
        for k, v in d["ray_actor_options"].items():
            lines.append(f"          {k}: {v}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------- handle-backed adapters


class _HandleSTT:
    """`STT` over a Serve deployment handle. Called from a worker thread."""

    def __init__(self, handle: Any) -> None:
        self.handle = handle

    def transcribe(self, audio: Any) -> Utterance:
        return self.handle.transcribe.remote(audio).result()

    def ready(self) -> bool:
        return bool(self.handle.ready.remote().result())


class _HandleLLM:
    def __init__(self, handle: Any) -> None:
        self.handle = handle

    def complete(self, messages: list[dict[str, str]]) -> str:
        return self.handle.complete.remote(messages).result()

    def stream(self, messages: list[dict[str, str]]):
        gen = self.handle.options(stream=True).stream.remote(messages)
        yield from gen

    def ready(self) -> bool:
        return bool(self.handle.ready.remote().result())


class _HandleTTS:
    def __init__(self, handle: Any, sample_rate: int = 24000) -> None:
        self.handle = handle
        self.sample_rate = sample_rate

    def synthesize(self, text: str) -> bytes:
        return self.handle.synthesize.remote(text).result()

    def ready(self) -> bool:
        return bool(self.handle.ready.remote().result())


def _make_deployments(config: dict[str, Any]) -> dict[str, Any]:
    """Define the Serve deployment classes. Requires `ray[serve]` and `fastapi`."""
    from ray import serve

    from vmp.serving.api import create_app
    from vmp.serving.backends import backends_from_config
    from vmp.serving.runtime import DEFAULT_SYSTEM_PROMPT, InMemorySessionStore, VoiceRuntime

    serving = config.get("serving", config)
    rs = _section(config)
    b = dict(_backends(config))
    llm_mode = str(rs.get("llm_mode", "openai-compat"))
    b["llm"] = "vllm" if llm_mode == "vllm" else "openai-compat"

    @serve.deployment(
        autoscaling_config=autoscaling_config(config, "stt"),
        ray_actor_options=ray_actor_options(config, "stt"),
    )
    class STTDeployment:
        def __init__(self) -> None:
            self.stt, _, _ = backends_from_config({"backends": b})

        def transcribe(self, audio: Any) -> Utterance:
            return self.stt.transcribe(audio)

        def ready(self) -> bool:
            fn = getattr(self.stt, "ready", None)
            return bool(fn()) if callable(fn) else True

    @serve.deployment(
        autoscaling_config=autoscaling_config(config, "llm"),
        ray_actor_options=ray_actor_options(config, "llm"),
    )
    class LLMDeployment:
        def __init__(self) -> None:
            _, self.llm, _ = backends_from_config({"backends": b})

        def complete(self, messages: list[dict[str, str]]) -> str:
            return self.llm.complete(messages)

        def stream(self, messages: list[dict[str, str]]):
            yield from self.llm.stream(messages)

        def ready(self) -> bool:
            fn = getattr(self.llm, "ready", None)
            return bool(fn()) if callable(fn) else True

    @serve.deployment(
        autoscaling_config=autoscaling_config(config, "tts"),
        ray_actor_options=ray_actor_options(config, "tts"),
    )
    class TTSDeployment:
        def __init__(self) -> None:
            _, _, self.tts = backends_from_config({"backends": b})

        def synthesize(self, text: str) -> bytes:
            return self.tts.synthesize(text)

        def sample_rate(self) -> int:
            return int(getattr(self.tts, "sample_rate", 24000))

        def ready(self) -> bool:
            fn = getattr(self.tts, "ready", None)
            return bool(fn()) if callable(fn) else True

    stt_h = STTDeployment.bind()
    llm_h = LLMDeployment.bind()
    tts_h = TTSDeployment.bind()

    runtime = VoiceRuntime(
        _HandleSTT(stt_h),
        _HandleLLM(llm_h),
        _HandleTTS(tts_h),
        system_prompt=str(serving.get("system_prompt", "")) or DEFAULT_SYSTEM_PROMPT,
        max_history_turns=int(serving.get("max_history_turns", 12)),
        max_context_chars=int(serving.get("max_context_chars", 1200)),
    )
    api = serving.get("api", {})
    fastapi_app = create_app(
        runtime,
        InMemorySessionStore(ttl_s=float(api.get("session_ttl_s", 3600.0))),
        max_request_bytes=int(api.get("max_request_bytes", 10 * 1024 * 1024)),
        turn_timeout_s=float(api.get("turn_timeout_s", 60.0)),
    )

    @serve.deployment(
        autoscaling_config=autoscaling_config(config, "ingress"),
        ray_actor_options=ray_actor_options(config, "ingress"),
    )
    @serve.ingress(fastapi_app)
    class VoiceAgentIngress:
        def __init__(self, stt: Any, llm: Any, tts: Any) -> None:
            # Replace bound nodes with live handles once the graph is deployed.
            runtime.stt = _HandleSTT(stt)
            runtime.llm = _HandleLLM(llm)
            runtime.tts = _HandleTTS(tts)

    return {
        "STTDeployment": STTDeployment,
        "LLMDeployment": LLMDeployment,
        "TTSDeployment": TTSDeployment,
        "VoiceAgentIngress": VoiceAgentIngress,
        "app": VoiceAgentIngress.bind(stt_h, llm_h, tts_h),
    }


def build_graph(config: dict[str, Any], dry_run: bool = False) -> Any:
    """Return the bound Serve application, or its description dict when `dry_run`."""
    if dry_run:
        return describe_graph(config)
    return _make_deployments(config)["app"]


def _config_from_env() -> dict[str, Any]:
    import os

    raw = os.environ.get("VMP_SERVING_CONFIG_JSON")
    if raw:
        return json.loads(raw)
    path = os.environ.get("VMP_SERVING_CONFIG", "configs/serving.toml")
    from vmp.config import load_config

    return load_config(path)


def __getattr__(name: str) -> Any:
    # `serve run vmp.serving.ray_serve:app` resolves `app` lazily so importing this
    # module never imports ray.
    if name == "app":
        return build_graph(_config_from_env())
    raise AttributeError(name)


__all__ = [
    "DEPLOYMENTS",
    "autoscaling_config",
    "build_graph",
    "describe_graph",
    "ray_actor_options",
    "serve_config_yaml",
]
