# Generated by vmp.features.feast_export for project 'vmp'. Do not edit.
from datetime import timedelta

from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float32, Int64, String

device = Entity(name="device", join_keys=["device_id"])

session = Entity(name="session", join_keys=["session_id"])

speaker = Entity(name="speaker", join_keys=["speaker_id"])

device_features_source = FileSource(
    path="data/device_features.parquet",
    timestamp_field="event_ts",
)

device_features = FeatureView(
    name="device_features",
    entities=[device],
    ttl=timedelta(seconds=86400),
    schema=[
        Field(name="edge_bundle_version", dtype=String),
        Field(name="p95_ttfa_ms_24h", dtype=Float32),
    ],
    online=True,
    source=device_features_source,
    tags={"source": "edge"},
    description='Edge device state and one-day latency percentile.',
)

session_features_source = FileSource(
    path="data/session_features.parquet",
    timestamp_field="event_ts",
)

session_features = FeatureView(
    name="session_features",
    entities=[session],
    ttl=timedelta(seconds=3600),
    schema=[
        Field(name="turn_count", dtype=Int64),
        Field(name="avg_user_utterance_s", dtype=Float32),
        Field(name="avg_response_ms", dtype=Float32),
        Field(name="last_intent", dtype=String),
        Field(name="accent_profile", dtype=String),
    ],
    online=True,
    source=session_features_source,
    tags={"source": "traces"},
    description='Rolling per-session features updated from stage traces.',
)

speaker_features_source = FileSource(
    path="data/speaker_features.parquet",
    timestamp_field="event_ts",
)

speaker_features = FeatureView(
    name="speaker_features",
    entities=[speaker],
    ttl=timedelta(seconds=604800),
    schema=[
        Field(name="wer_7d", dtype=Float32),
        Field(name="exact_match_rate_7d", dtype=Float32),
        Field(name="wake_word_corrections_7d", dtype=Int64),
    ],
    online=True,
    source=speaker_features_source,
    tags={"source": "eval"},
    description='Seven-day quality aggregates per speaker, from evaluation runs.',
)
